# Generated by Django 5.2.8 on 2025-11-19 14:43

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name": "Home Page", "verbose_name_plural": "Home Pages"},
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_block",
            field=wagtail.fields.StreamField(
                [("about_section", 4)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Heading for About section",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Main content; supports rich text",
                            "required": True,
                        },
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Image for About section", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Check to reverse image/text layout on desktop",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 0),
                                ("content", 1),
                                ("image", 2),
                                ("reverse_layout", 3),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("hero_section", 5), ("paragraph", 6)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Main heading for the hero section",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Optional subtitle", "required": False},
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Background image for the hero section",
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Button URL for call to action",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("var(--primary)", "Primary"),
                                ("var(--secondary)", "Secondary"),
                                ("var(--accent)", "Accent"),
                            ],
                            "help_text": "Optional overlay color (matches global CSS variables)",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 1),
                                ("background_image", 2),
                                ("call_to_action", 3),
                                ("overlay_color", 4),
                            ]
                        ],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"icon": "pilcrow", "template": "blocks/rich_text_block.html"},
                    ),
                },
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="cta_block",
            field=wagtail.fields.StreamField(
                [("cta_section", 7)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": True},
                    ),
                    1: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text for CTA button",
                            "max_length": 30,
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "URL for CTA button", "required": True},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("button_text", 2), ("button_url", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.ListBlock",
                        (4,),
                        {"help_text": "Add one or more buttons"},
                    ),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("var(--primary)", "Primary"),
                                ("var(--secondary)", "Secondary"),
                                ("var(--accent)", "Accent"),
                            ],
                            "help_text": "Optional background color for CTA section",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 0),
                                ("subheading", 1),
                                ("buttons", 5),
                                ("background_color", 6),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="gallery_block",
            field=wagtail.fields.StreamField(
                [("gallery_section", 4)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": True},
                    ),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    2: (
                        "wagtail.blocks.ListBlock",
                        (1,),
                        {"help_text": "Add multiple images to gallery"},
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("grid", "Grid"), ("carousel", "Carousel")],
                            "help_text": "Choose layout for the gallery",
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("images", 2), ("gallery_layout", 3)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="newsletter_block",
            field=wagtail.fields.StreamField(
                [("newsletter_section", 4)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": True},
                    ),
                    1: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    2: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "AJAX submission URL for newsletter form",
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Subscribe", "max_length": 20, "required": True},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 0),
                                ("subheading", 1),
                                ("form_action_url", 2),
                                ("submit_button_text", 3),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="services_block",
            field=wagtail.fields.StreamField(
                [("services_section", 6)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": True},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 50, "required": True},
                    ),
                    2: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"max_length": 250, "required": True},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Bulma or FontAwesome icon class",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("description", 2), ("icon_name", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.ListBlock",
                        (4,),
                        {"help_text": "Add multiple services or programs"},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("services_list", 5)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="subtitle",
            field=models.CharField(
                blank=True,
                help_text="Optional subtitle for the homepage",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="testimonial_block",
            field=wagtail.fields.StreamField(
                [("testimonials_section", 7)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": True},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 50, "required": True},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 50, "required": False},
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"max_length": 300, "required": True},
                    ),
                    4: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Optional image/avatar of the person",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 1), ("role", 2), ("content", 3), ("avatar", 4)]],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.ListBlock",
                        (5,),
                        {"help_text": "Add multiple testimonials"},
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("testimonials", 6)]],
                        {},
                    ),
                },
            ),
        ),
    ]
