# Generated by Django 5.2.8 on 2025-11-19 14:44

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_homepage_options_homepage_about_block_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="body",
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_block",
            field=wagtail.fields.StreamField(
                [("hero_section", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Main heading for the hero section",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Optional subtitle", "required": False},
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Background image for the hero section",
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Button URL for call to action",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("var(--primary)", "Primary"),
                                ("var(--secondary)", "Secondary"),
                                ("var(--accent)", "Accent"),
                            ],
                            "help_text": "Optional overlay color (matches global CSS variables)",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 1),
                                ("background_image", 2),
                                ("call_to_action", 3),
                                ("overlay_color", 4),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
