# Generated by Django 5.2.8 on 2025-11-19 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_remove_homepage_body_homepage_hero_block"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homepage",
            old_name="subtitle",
            new_name="home_title",
        ),
    ]
