# Generated by Django 5.2.8 on 2025-11-19 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_rename_subtitle_homepage_home_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homepage",
            old_name="home_title",
            new_name="subtitle",
        ),
    ]
